<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Entities\Academic\**" />
    <EmbeddedResource Remove="Entities\Academic\**" />
    <None Remove="Entities\Academic\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="BaseModels\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="11.0.1" />
    <PackageReference Include="ClosedXML" Version="0.95.4" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="6.0.3" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Include="MimeKit" Version="4.8.0" />
    <PackageReference Include="Nancy" Version="2.0.0" />
  </ItemGroup>

</Project>
