<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="11.0.1" />
    <PackageReference Include="iTextSharp" Version="5.5.13.3" />
    <PackageReference Include="itextsharp.xmlworker" Version="5.5.13.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Interface\Interface.csproj" />
    <ProjectReference Include="..\..\Core\Services\Services.csproj" />
    <ProjectReference Include="..\Repository\Repository.csproj" />
  </ItemGroup>

</Project>
